//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventosApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventosApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4f357b1cdf0b1a11ec08919f83a5b9261e608b14_s2_n3_y2 {
            get {
                object obj = ResourceManager.GetObject("4f357b1cdf0b1a11ec08919f83a5b9261e608b14_s2_n3_y2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _545f7f44fdf90d6848f56e967b6ab9b4 {
            get {
                object obj = ResourceManager.GetObject("545f7f44fdf90d6848f56e967b6ab9b4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6a24da1e86dda36f32d45b9b39928236c92fce4e_s2_n3_y1 {
            get {
                object obj = ResourceManager.GetObject("6a24da1e86dda36f32d45b9b39928236c92fce4e_s2_n3_y1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b8e4addf9ab1d774e0c6491b4d67cdb6 {
            get {
                object obj = ResourceManager.GetObject("b8e4addf9ab1d774e0c6491b4d67cdb6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b8e4addf9ab1d774e0c6491b4d67cdb61 {
            get {
                object obj = ResourceManager.GetObject("b8e4addf9ab1d774e0c6491b4d67cdb61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b8e4addf9ab1d774e0c6491b4d67cdb62 {
            get {
                object obj = ResourceManager.GetObject("b8e4addf9ab1d774e0c6491b4d67cdb62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b8ff725e8ac6cdadec96d428e00e8e22 {
            get {
                object obj = ResourceManager.GetObject("b8ff725e8ac6cdadec96d428e00e8e22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dc161b749df92cdd2c8e5ac2d310707bc9af1dc6_s2_n3_y2 {
            get {
                object obj = ResourceManager.GetObject("dc161b749df92cdd2c8e5ac2d310707bc9af1dc6_s2_n3_y2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dc161b749df92cdd2c8e5ac2d310707bc9af1dc6_s2_n3_y21 {
            get {
                object obj = ResourceManager.GetObject("dc161b749df92cdd2c8e5ac2d310707bc9af1dc6_s2_n3_y21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap decc2dbc1ae38ce4ece31a8b328cb5babfb9322d_s2_n3_y1 {
            get {
                object obj = ResourceManager.GetObject("decc2dbc1ae38ce4ece31a8b328cb5babfb9322d_s2_n3_y1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_remove_close_icon_181533 {
            get {
                object obj = ResourceManager.GetObject("delete_remove_close_icon_181533", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap evento {
            get {
                object obj = ResourceManager.GetObject("evento", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FondoRegistrarse {
            get {
                object obj = ResourceManager.GetObject("FondoRegistrarse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Granate_Sofisticado_Vintage_Reyes_Magos_Navidad_Eventos_e_Interés_Especial_Presentación {
            get {
                object obj = ResourceManager.GetObject("Granate Sofisticado Vintage Reyes Magos Navidad Eventos e Interés Especial Presen" +
                        "tación", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Granate_Sofisticado_Vintage_Reyes_Magos_Navidad_Eventos_e_Interés_Especial_Presentación1 {
            get {
                object obj = ResourceManager.GetObject("Granate Sofisticado Vintage Reyes Magos Navidad Eventos e Interés Especial Presen" +
                        "tación1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Granate_Sofisticado_Vintage_Reyes_Magos_Navidad_Eventos_e_Interés_Especial_Presentación2 {
            get {
                object obj = ResourceManager.GetObject("Granate Sofisticado Vintage Reyes Magos Navidad Eventos e Interés Especial Presen" +
                        "tación2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_arrow_2_icon_icons_com_62881 {
            get {
                object obj = ResourceManager.GetObject("left-arrow-2_icon-icons.com_62881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pen_edit_modify_pencil_icon_181536 {
            get {
                object obj = ResourceManager.GetObject("pen_edit_modify_pencil_icon_181536", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap perrito {
            get {
                object obj = ResourceManager.GetObject("perrito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_insert_add_new_icon_181537 {
            get {
                object obj = ResourceManager.GetObject("plus_insert_add_new_icon_181537", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap semifondo {
            get {
                object obj = ResourceManager.GetObject("semifondo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap semifondotrabajadores {
            get {
                object obj = ResourceManager.GetObject("semifondotrabajadores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
